### ISSUE TITLE
有没有好点的站点分享

### ISSUE THREAD

**Issue by Zoranner** [loremwalker/WebSiteUseful#18]
那种看到之后不愿意不舍得跟别人分享的，这些站太普通了。

P.S.你低估了墙的价值，而且墙也只是为了围困低阶群众。再坚持坚持，墙快要完成现阶段的使命了。

<sub>Sent from <a href="https://itunes.apple.com/cn/app/id1314212521">PPHub For GitHub</a></sub>

**Comment by loremwalker** [comment]
gud 4 u.  你是精英阶层知识分子 你很优秀！

获取 Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by yuanil** [comment]
没有，速度快的收费


------------------ 原始邮件 ------------------
发件人: "杨新冉"<notifications@github.com>;
发送时间: 2019年5月5日(星期天) 下午4:05
收件人: "loremwalker/WebSiteUseful"<WebSiteUseful@noreply.github.com>;
抄送: "Subscribed"<subscribed@noreply.github.com>; 
主题: [loremwalker/WebSiteUseful] 有没有好点的站点分享 (#18)




那种看到之后不愿意不舍得跟别人分享的，这些站太普通了。
 
P.S.你低估了墙的价值，而且墙也只是为了围困低阶群众。再坚持坚持，墙快要完成现阶段的使命了。
 
Sent from PPHub For GitHub

**Comment by Zoranner** [comment]
不不不 我也是低阶屁民 只是长期感受不到墙的存在看得略清楚一些而已 另外也是真心寻求一些比较好的站点

________________________________
发件人: lorem <notifications@github.com>
发送时间: Sunday, May 5, 2019 5:09:46 PM
收件人: loremwalker/WebSiteUseful
抄送: 杨新冉; Author
主题: Re: [loremwalker/WebSiteUseful] 有没有好点的站点分享 (#18)

gud 4 u. 你是精英阶层知识分子 你很优秀！

获取 Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by Zoranner** [comment]
嗯 我是想找一些好的网站站点 不是VPN站点 我自己有大批国外服务器不担心翻墙

________________________________
发件人: 月光 <notifications@github.com>
发送时间: 星期日, 五月 5, 2019 5:15 下午
收件人: loremwalker/WebSiteUseful
抄送: 杨新冉; Author
主题: Re: [loremwalker/WebSiteUseful] 有没有好点的站点分享 (#18)

没有，速度快的收费


------------------ 原始邮件 ------------------
发件人: "杨新冉"<notifications@github.com>;
发送时间: 2019年5月5日(星期天) 下午4:05
收件人: "loremwalker/WebSiteUseful"<WebSiteUseful@noreply.github.com>;
抄送: "Subscribed"<subscribed@noreply.github.com>;
主题: [loremwalker/WebSiteUseful] 有没有好点的站点分享 (#18)




那种看到之后不愿意不舍得跟别人分享的，这些站太普通了。

P.S.你低估了墙的价值，而且墙也只是为了围困低阶群众。再坚持坚持，墙快要完成现阶段的使命了。

Sent from PPHub For GitHub

―
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or mute the thread.

―

**Comment by yuanil** [comment]
(⊙o⊙)哦，没......咱差不多也是初接触，名副其实的小白。


------------------ 原始邮件 ------------------
发件人: "杨新冉"<notifications@github.com>;
发送时间: 2019年5月5日(星期天) 下午5:28
收件人: "loremwalker/WebSiteUseful"<WebSiteUseful@noreply.github.com>;
抄送: "鲁迅"<2502725335@qq.com>; "Comment"<comment@noreply.github.com>; 
主题: Re: [loremwalker/WebSiteUseful] 有没有好点的站点分享 (#18)



嗯 我是想找一些好的网站站点 不是VPN站点 我自己有大批国外服务器不担心翻墙 
 
 ________________________________ 
 发件人: 月光 <notifications@github.com> 
 发送时间: 星期日, 五月 5, 2019 5:15 下午 
 收件人: loremwalker/WebSiteUseful 
 抄送: 杨新冉; Author 
 主题: Re: [loremwalker/WebSiteUseful] 有没有好点的站点分享 (#18) 
 
 没有，速度快的收费 
 
 
 ------------------ 原始邮件 ------------------ 
 发件人: "杨新冉"<notifications@github.com>; 
 发送时间: 2019年5月5日(星期天) 下午4:05 
 收件人: "loremwalker/WebSiteUseful"<WebSiteUseful@noreply.github.com>; 
 抄送: "Subscribed"<subscribed@noreply.github.com>; 
 主题: [loremwalker/WebSiteUseful] 有没有好点的站点分享 (#18) 
 
 
 
 
 那种看到之后不愿意不舍得跟别人分享的，这些站太普通了。 
 
 P.S.你低估了墙的价值，而且墙也只是为了围困低阶群众。再坚持坚持，墙快要完成现阶段的使命了。 
 
 Sent from PPHub For GitHub 
 
 ― 
 You are receiving this because you are subscribed to this thread. 
 Reply to this email directly, view it on GitHub, or mute the thread. 
 
 ―
